version: '3'

services:
  web:
    build:
      context: app
      target: builder
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html/
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: asknicely
      MYSQL_USER: user
      MYSQL_PASSWORD: your_password

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: asknicely
      MYSQL_USER: user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
